Extracted unlocked-did into an environment var
digitalcredentials/sign-and-verify pull request #5
Opened 2020-10-05 19:53 UTC by rhysyngsun

Part of #1 

This extracts the statically loaded `unloaded-did*.json` file into a base64-encoded environment variable.

Also a few other things that were done to support this:

- Extracted `process.env` parsing into `config.ts`
- Added tests for the new code
- Updated existing `require()` usages to use `import` instead (a few `@types/*` dependencies added to support this
- Tweaked the docker-compose setup to support iterative testing without having to rebuild the container

2020-10-06 14:01 UTC, aliceriot commented
is the plan to continue to support running the service locally, for development, outside of docker-compose? If so I think a few tweaks will be needed, possibly adding something like [dotenv](https://www.npmjs.com/package/dotenv) to parse a `.env` file for configuration.

2020-10-06 14:16 UTC, aliceriot requested changes
works great with the docker setup, just had a few questions / comments on things

2020-10-06 16:58 UTC, rhysyngsun commented on types/vc-js/index.d.ts
> +declare module 'vc-js';
Yeah, typescript fails on them when you `import` them. Previously they were `require`'d, which typescript doesn't type-check. These defs just basically type the whole module as `any`.

2020-10-06 17:58 UTC, aliceriot commented on types/vc-js/index.d.ts
> +declare module 'vc-js';
gotcha, makes sense!

2020-10-06 18:06 UTC, kimdhamilton approved these changes

2020-10-07 13:40 UTC, aliceriot approved these changes
just noticed one little formatting thing, otherwise looks good!

2020-10-07 13:40 UTC, aliceriot commented on src/config.ts
> +
stray empty line? we might wanna throw prettier on here at some point

2020-10-07 14:15 UTC, merged